# Generated by Django 4.2.1 on 2023-05-29 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('course_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_courses.coursegeneral')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('course_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_courses.courseparts')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_tests', models.IntegerField()),
                ('count_correct', models.IntegerField()),
                ('test_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_courses.coursesubject')),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('message_date', models.DateField()),
                ('user_reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reciver', to=settings.AUTH_USER_MODEL)),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideoLections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lection_video', models.FileField(upload_to='videos/')),
                ('lection_title', models.CharField(max_length=50)),
                ('subject_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_courses.coursesubject')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_question', models.TextField()),
                ('test_option1', models.CharField(max_length=30)),
                ('test_option2', models.CharField(max_length=30)),
                ('test_option3', models.CharField(max_length=30)),
                ('test_option4', models.CharField(max_length=30)),
                ('test_answer', models.CharField(max_length=30)),
                ('course_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_courses.coursesubject')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lection_title', models.CharField(max_length=50)),
                ('lection_text', models.TextField()),
                ('lection_image', models.ImageField(upload_to='')),
                ('subject_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_courses.coursesubject')),
            ],
        ),
    ]
