# Generated by Django 4.2.1 on 2023-05-29 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_courses', '0003_coursegeneral_course_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegeneral',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
