# Generated by Django 4.2.1 on 2023-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0004_alter_coursegeneral_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegeneral',
            name='course_icon',
            field=models.ImageField(blank=True, default='qwert', upload_to='media/'),
        ),
    ]
