# Generated by Django 4.2.1 on 2023-05-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0006_usercoursesubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluserinfo',
            name='user_icon',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
