# Generated by Django 4.2.1 on 2023-05-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0007_alter_alluserinfo_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluserinfo',
            name='user_icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
