# Generated by Django 4.2.1 on 2023-05-30 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0008_alter_alluserinfo_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubject',
            name='course_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_courses.coursegeneral'),
        ),
    ]
