# Generated by Django 4.2.1 on 2023-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0009_alter_coursesubject_course_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselections',
            name='lection_text',
        ),
        migrations.AddField(
            model_name='courselections',
            name='lection_text1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='courselections',
            name='lection_text2',
            field=models.TextField(default=''),
        ),
    ]
