# Generated by Django 4.2.1 on 2023-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0010_remove_courselections_lection_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselections',
            name='lection_image',
            field=models.ImageField(blank=True, default='qwert', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='coursevideolections',
            name='lection_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
