# Generated by Django 4.2.1 on 2023-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0011_alter_courselections_lection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegeneral',
            name='course_icon',
            field=models.ImageField(blank=True, default='qwert', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='courselections',
            name='lection_image',
            field=models.ImageField(blank=True, default='qwert', null=True, upload_to='media/'),
        ),
    ]
